import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar"
import Lenis from "./components/lenis";
import  React  from "react";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import gsap from "gsap";
gsap.registerPlugin(ScrollTrigger)


const Onsite = localFont({
  src: "./fonts/OnsiteStandardTRIAL-Regular-BF64b60bd6980ca.otf",
  variable: "--font-Onsite",
  weight: "400 500 600 700"
});


export const metadata = {
  title: "Curve",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>){


  return (
    <html lang="en">
      <body
        className={`${Onsite.variable} bg-[#0E090D] antialiased `}
      >
        <Lenis>
          <Navbar/>
          {children}
        </Lenis>
      </body>
    </html>
  );
}
